Process non-default variable assignment as command parameters

diff --git a/lmdescrypt b/lmdescrypt
--- a/lmdescrypt
+++ b/lmdescrypt
@@ -1,11 +1,13 @@
 #!/bin/bash
-set +o xtrace +o verbose +o errexit -o errtrace
-trap 'set +o xtrace +o verbose +o errexit +o errtrace; return 1' INT TERM
-version=0.989
+set +o xtrace +o verbose -o errexit -o errtrace
+trap 'set +o errexit; return 1' ERR
+trap 'echo Exit' EXIT
+trap 'set +o xtrace +o verbose +o errexit +o errtrace; return 2' INT TERM
+version=0.990
 
 ############################################################################
 #
-#  lmdescrypt 0.989
+#  lmdescrypt 0.990
 #
 # Download shortlinks: https://4e4.win/lm or http://j.mp/lmdescrypt
 #
@@ -18,7 +20,8 @@ version=0.989
 #  (with optional boot-from-iso-file).
 #
 # Shortlink to download the script: http://4e4.win/lmdescrypt
-# Tutorial on Linux Mint community: https://community.linuxmint.com/tutorial/view/2265
+# Tutorial on Linux Mint community:
+#  https://community.linuxmint.com/tutorial/view/2265
 # Gitlab page: https://gitlab.com/pepa65/lmdescrypt
 # Questions? Email pepa65@passchier.net or post an Issue on the gitlab page.
 #
@@ -69,8 +72,8 @@ version=0.989
 ### And that's it!
 ##
 ### Installing into a pre-existing environment
-##  Using a pre-existing boot-partition, LUKS partition and LVM Logical Volumes
-##   is entirely supported.
+##  Using a pre-existing boot-partition, LUKS partition and LVM Logical
+##   Volumes is entirely supported.
 ##  Not having a separate boot partition is also supported: total encryption!
 ##  Multiple boot setups with other OSes also works out of the box.
 ##  MBR, GPT partition tables and UEFI work according to configuration.
@@ -91,7 +94,7 @@ grub_device=/dev/sda
 ## Total encryption: boot_part should be empty
 ## UEFI setup: Must have an efi partition (type ef00) of at least 260M with a
 ##  VFAT filesystem, will be formatted if not yet formatted!
-## GPT (non-UEFI) setup: Must have a bios partition (type ef02) of at least 2M!
+## GPT non-UEFI setup: Must have a bios partition (type ef02) of at least 2M!
 ### Partitions to use:
 boot_part=
 crypt_part=/dev/sda2
@@ -182,14 +185,16 @@ packages=''
 ############################################################################
 
 Echo(){ ## $1=message
-	echo -e '_______________________________________________________________________________\n'
+	echo -n '________________________________________________________________'
+	echo -e '_______________\n'
 	echo -e "  $1"
-	echo -e '_______________________________________________________________________________\n'
+	echo -n '________________________________________________________________'
+	echo -e '_______________\n'
 }
 
 ## To really exit it needs to be followed by 'return' in the main body!
 Exit(){ ## $1=message
-	Echo "  ERROR: $1\n  ABORTING"
+	Echo "ERROR: $1\n  ABORTING"
 }
 
 Warning(){ ## $1=message
@@ -198,7 +203,7 @@ Warning(){ ## $1=message
 
 Mkfs(){ ## $1=fs $2=label $3=dev $4=kind
 	case $1 in
-		hfs|hfsplus|jfs|minix|msdos|vfat|ntfs) [[ ! $4 = data ]] && return 2 ;;&
+		hfs|hfsplus|jfs|minix|msdos|vfat|ntfs) [[ ! $4 = data ]] && return 3 ;;&
 		## Continue even if the above pattern matched (unless $4 isn't data)
 		btrfs) mkfs.$1 -f -L "$2" "$3" ;;
 		ext2|ext3|ext4) mkfs.$1 -F -L "$2" "$3" ;;
@@ -210,7 +215,7 @@ Mkfs(){ ## $1=fs $2=label $3=dev $4=kind
 		ntfs) mkfs.$1 -f -F -U -L "$2" "$3" ;;
 		reiserfs) mkfs.$1 -ffl "$2" "$3" ;;
 		xfs) mkfs.$1 -f -L "$2" "$3" ;;
-		*) return 3 ;;
+		*) return 4 ;;
 	esac
 }
 
@@ -229,45 +234,59 @@ Checklabel(){ ## $1: labelname
 self=$(basename $BASH_SOURCE)
 
 ## If not run interactively, don't run
-[[ $- != *i* ]] && Exit "  ERROR: This script needs to be sourced! Run it like:\n   sudo source $self\n  ABORTING" && exit 1
-((EUID)) && Exit "This script only works when run with root privileges, like:\n   sudo source $self" && return 4
+[[ $- != *i* ]] &&
+	Exit "Must be sourced! Run it like:\n   source $self" &&
+	exit 1
+((EUID)) &&
+	Exit "Must be run with root privileges, do:\n   sudo -i\n   source $self" &&
+	return 5
 
+## Set parameters from commandline
+for p in "$@"
+do
+	[[ ! $p =~ ^[a-z_][a-z0-9_]*= ]] &&
+		Exit "No variable assignment: $p" && return 6
+	q="${p/=/=\'}'"
+	! eval "$q" && Exit "Failed argument evaluation: '$p'" && return 7
+	echo "    ${q%%=*}: ${q#*=}"
+done
+sleep 9999
 ## Check existence of mandatory devices
 [[ ! -w "$crypt_part" ]] &&
 	Exit "Crypt device does not exist or is not writable: '$crypt_part'" &&
-	return 5
+	return 8
 [[ ! -w "$grub_device" ]] &&
 	Exit "Grub device does not exist or is not writable: '$grub_device'" &&
-	return 6
+	return 9
 
 ## Check names, labels, root_fs
 [[ ! $username =~ ^[a-z_][a-z0-9_]*$ ]] &&
-	Exit "Illegal format for username: '$username'" && return 7
+	Exit "Illegal format for username: '$username'" && return 10
 [[ ! $hostname =~ ^[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]$ ]] &&
-	Exit "Illegal format for hostname: '$hostname'" && return 8
-Checklabel crypt && return 9
-Checklabel vg && return 10
-Checklabel boot && return 11
-Checklabel root && return 12
-Checklabel swap && return 13
-Checklabel data && return 14
+	Exit "Illegal format for hostname: '$hostname'" && return 11
+Checklabel crypt && return 12
+Checklabel vg && return 13
+Checklabel boot && return 14
+Checklabel root && return 15
+Checklabel swap && return 16
+Checklabel data && return 17
 [[ ! $root_fs =~ ^(btrfs|ext2|ext3|ext4|reiserfs|xfs|)$ ]] &&
-	Exit "Wrong value for root_fs: '$root_fs'" && return 15
+	Exit "Wrong value for root_fs: '$root_fs'" && return 18
 
 ## Determine root and data partition usage & size
-[[ $root_size ]] && [[ ! $root_size = REST ]] && [[ ! $root_size = EXISTING ]] &&
-	[[ ! $root_size =~ [1-9][0-9]*[MG] ]] &&
-	Exit "Invalid format root_size: '$root_size'" && return 16
+[[ $root_size ]] && [[ ! $root_size = REST ]] &&
+	[[ ! $root_size = EXISTING ]] && [[ ! $root_size =~ [1-9][0-9]*[MG] ]] &&
+	Exit "Invalid format root_size: '$root_size'" && return 19
 if [[ $data_size = REST ]]
 then
 	[[ $root_size = REST ]] &&
-		Exit "Settings data_size and root_size can't both be REST" && return 17
+		Exit "Settings data_size and root_size can't both be REST" && return 20
 	lvm_data='-l 100%FREE -Zy'
 else
 	if [[ $data_size && ! $data_size = EXISTING ]]
 	then
 		[[ ! $data_size =~ [1-9][0-9]*[MG] ]] &&
-			Exit "Invalid format data_size: '$data_size'" && return 18
+			Exit "Invalid format data_size: '$data_size'" && return 21
 		lvm_data="-L $data_size -Zy"
 	fi
 fi
@@ -280,7 +299,7 @@ else
 	if [[ ! $swap_size = EXISTING ]]
 	then
 		[[ $swap_size ]] && [[ ! $swap_size =~ [1-9][0-9]*[MG] ]] &&
-			Exit "Invalid format swap_size: $swap_size" && return 19
+			Exit "Invalid format swap_size: $swap_size" && return 22
 		lvm_swap="-L $swap_size -Cy -Zy"
 	fi
 fi
@@ -293,13 +312,13 @@ then  ## GPT partition scheme
 	if [[ -e /sys/firmware/efi ]]
 	then  ## UEFI: so it is an amd64 architecture that supports UEFI
 		read n discard <<<"$(grep ' EF00  ' <<<"$gdisk" |head -1)"
-		[[ -z $n ]] && Exit "UEFI without type ef00 efi partition!" && return 20
+		[[ -z $n ]] && Exit "UEFI without type ef00 efi partition!" && return 23
 		efi_part="$grub_device$n"
 		[[ ! $(lsblk "$efi_part" -no FSTYPE) = vfat ]] &&
 			mkfs.vfat -n EFI "$efi_part"
 	else  ## non-UEFI GPT setup
 		! grep -q ' EF02  ' <<<"$gdisk" &&
-			Exit "Non-UEFI GPT setup without type ef02 bios partition" && return 21
+			Exit "Non-UEFI GPT setup without type ef02 bios partition" && return 24
 	fi
 fi
 
@@ -316,8 +335,8 @@ do
 	then
 		/lib/cryptsetup/askpass "Enter the same password again:" >"$pwf2"
 		echo
-		diff -q --label $'\b\b\b\b\b\b\b\bFirst' "$pwf" --label "second password" "$pwf2" ||
-			shred -u "$pwf"
+		diff -q --label $'\b\b\b\b\b\b\b\bFirst' "$pwf" \
+				--label "second password" "$pwf2" || shred -u "$pwf"
 		shred -u "$pwf2"
 	else
 		echo -e "Empty password not allowed\n"
@@ -345,8 +364,8 @@ fi
 crypt_dev="/dev/mapper/$crypt_label"
 [[ ! -b "$crypt_dev" ]] &&
 	! cryptsetup luksOpen "$crypt_part" $crypt_label --key-file "$pwf" &&
-	shred -u "$pwf" && Exit "Failed to open the encrypted partition $crypt_part" &&
-	return 22
+	shred -u "$pwf" &&
+		Exit "Failed to open the encrypted partition $crypt_part" && return 25
 shred -u "$pwf"
 crypt_uuid=$(blkid -s UUID -o value "$crypt_part")
 
@@ -366,7 +385,7 @@ then
 	if [[ $swap_fs ]]
 	then
 		[[ ! $swap_fs = swap ]] && Exit "Wrong value for swap_fs: '$swap_fs'" &&
-			return 23 ||
+			return 26 ||
 			mkswap -f -L $swap_label "$swap_dev"
 	fi
 fi
@@ -377,22 +396,22 @@ fi
 if [[ $data_size ]]
 then  ## Create if it doesn't exist and format if required
 	[[ ! -h $data_dev && $data_size = EXISTING ]] &&
-		Exit "There is no existing data device $data_dev" && return 24
+		Exit "There is no existing data device $data_dev" && return 27
 		lvcreate -Wy $lvm_data -n $data_label $vg_label
 	if [[ $data_fs ]]
 	then
 		! Mkfs "$data_fs" "$data_label" "$data_dev" data &&
 			Exit "Unsupported filesystem $data_fs for data volume $data_dev with label $data_label" &&
-			return 25
+			return 28
 	else  ## No data filesystem specified: existing or bust
 		if [[ $data_size = EXISTING ]]
 		then
 			! data_fs=$(lsblk "$data_dev" -no FSTYPE 2>/dev/null) &&
 				Exit "No filesystem specified for data volumeand none present" &&
-				return 26
+				return 29
 		else
 			Exit "No filesystem specified for data volume"
-			return 27
+			return 30
 		fi
 	fi
 fi
@@ -402,30 +421,30 @@ if [[ $root_fs ]]
 then
 	! Mkfs "$root_fs" "$root_label" "$root_dev" root &&
 		Exit "Unsupported filesystem $root_fs for root-device $root_dev with label $root_label" &&
-		return 28
+		return 31
 else
 	root_fs=$(lsblk "$root_dev" -no FSTYPE 2>/dev/null)
 	[[ -z $root_fs ]] &&
 		Exit "Root volume is not has no filesystem, fill in 'root_fs'" &&
-		return 29
+		return 32
 	[[ $root_fs =~ ^(btrfs|ext2|ext3|ext4|reiserfs|xfs)$ ]] &&
-		Exit "Root partition has unsupported filesystem: $root_fs" && return 30
+		Exit "Root partition has unsupported filesystem: $root_fs" && return 33
 fi
 
 if [[ $boot_part ]]
 then
 	[[ ! $boot_fs =~ ^(btrfs|ext2|ext3|ext4|reiserfs|xfs|)$ ]] &&
-		Exit "Wrong value for boot_fs: '$boot_fs'" && return 31
+		Exit "Wrong value for boot_fs: '$boot_fs'" && return 34
 	if [[ $boot_fs ]]
 	then
 		! Mkfs "$boot_fs" "$boot_label" "$boot_part" boot &&
 			Exit "Unsupported filesystem $boot_fs for boot-device $boot_part with label $boot_label" &&
-			return 32
+			return 35
 	else
 		boot_fs=$(lsblk "$boot_part" -no FSTYPE 2>/dev/null)
 		[[ -z $boot_fs ]] &&
 			Exit "Boot partition $boot_part has no filesystem, fill in 'boot_fs' (or leave boot_part empty)" &&
-			return 33
+			return 36
 	fi
 	boot_uuid=$(blkid -s UUID -o value "$boot_part")
 fi
@@ -469,9 +488,12 @@ grep -q '^ID=ubuntu' <<<"$osrelease" && apt-add-repository universe
 echo "proc /proc proc defaults 0 0" >"$target/etc/fstab"
 [[ $root_fs = btrfs ]] &&
 	echo "$root_dev / $root_fs defaults,compress 0 1" >>"$target/etc/fstab" ||
-	echo "$root_dev / $root_fs defaults,relatime,errors=remount-ro 0 1" >>"$target/etc/fstab"
-[[ $swap_size ]] && echo "$swap_dev $swap_label swap sw 0 0" >>"$target/etc/fstab"
-[[ $data_size ]] && echo "$data_dev /$data_label $data_fs relatime 0 2" >>"$target/etc/fstab"
+	echo "$root_dev / $root_fs defaults,relatime,errors=remount-ro 0 1" \
+			>>"$target/etc/fstab"
+[[ $swap_size ]] &&
+	echo "$swap_dev $swap_label swap sw 0 0" >>"$target/etc/fstab"
+[[ $data_size ]] &&
+	echo "$data_dev /$data_label $data_fs relatime 0 2" >>"$target/etc/fstab"
 p3=none p4=luks
 if [[ -z $boot_part ]]
 then
@@ -538,7 +560,7 @@ mount --bind /dev "$target/dev"
 
 ## Prepare the chroot script
 inside="/root/$self.inside"
-( # Subshell start
+( ## Subshell start
 cat <<X
 #!/bin/bash
 set +o verbose -o errtrace
@@ -561,8 +583,8 @@ do
 	then
 		/lib/cryptsetup/askpass "Enter the same password again: " >"\$pwf2"
 		echo
-		diff -q --label \$'\b\b\b\b\b\b\b\bFirst' "\$pwf" --label "second password"	"\$pwf2" ||
-			shred -u "\$pwf"
+		diff -q --label \$'\b\b\b\b\b\b\b\bFirst' "\$pwf" \
+				--label "second password"	"\$pwf2" || shred -u "\$pwf"
 		shred "\$pwf2"
 	else
 		echo -e "Empty password not allowed\n"
@@ -603,9 +625,12 @@ then
 	mkdir -p "$efi_dir"
 	mount "$efi_part" "$efi_dir"
 	mkdir -p "$efi_dir/EFI/boot"
-	DEBIAN_FRONTEND=noninteractive apt install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --yes --force-yes grub-efi mokutil
+	DEBIAN_FRONTEND=noninteractive apt install \
+			-o Dpkg::Options::="--force-confdef" \
+			-o Dpkg::Options::="--force-confold" --yes --force-yes grub-efi mokutil
 	grub-install --force --recheck --target=x86_64-efi --efi-directory="$efi_dir" "$grub_device"
-	grep -q '^Linux Mint 17' /etc/issue && sed -i 's/^quick_boot="1"/quick_boot="0"/g' /etc/grub.d/*
+	grep -q '^Linux Mint 17' /etc/issue &&
+		sed -i 's/^quick_boot="1"/quick_boot="0"/g' /etc/grub.d/*
 	update-grub
 	cp "$efi_dir"/EFI/*/grubx64.efi "$efi_dir/EFI/boot/bootx64.efi"
 	umount "$efi_dir"
@@ -623,7 +648,7 @@ umount /sys
 [[ -f /lvm.pid ]] && kill -9 \$(cat /lvm.pid) && rm /lvm.pid
 exit 0
 X
-# End of subshell
+## Subshell end
 ) >"$target$inside"
 chmod +x "$target$inside"
 
@@ -632,9 +657,9 @@ Echo "Finalizing settings on the install"
 chroot "$target" "$inside"
 
 [[ $(df --output=pcent $target |tail -1) = 100% ]] &&
-	Exit "The filesystem on $root_dev is 100% full" && return 34
+	Exit "The filesystem on $root_dev is 100% full" && return 37
 [[ $boot_part && $(df --output=pcent $target/boot |tail -1) = 100% ]] &&
-	Exit "The filesystem on $boot_part is 100% full" && return 35
+	Exit "The filesystem on $boot_part is 100% full" && return 38
 
 umount "$target/dev"
 [[ $boot_part ]] && umount "$target/boot"
@@ -643,11 +668,12 @@ umount "$target"
 [[ $swap_size ]] && swapoff "$swap_dev"
 sync
 sleep 1
-! vgchange -an && Exit "Not able to close all logical volumes" && return 36
+! vgchange -an && Exit "Not able to close all logical volumes" && return 39
 sync
 sleep 1
-! cryptsetup luksClose $crypt_label && Exit "Not able to cleanly close crypt" &&
-	return 37
+! cryptsetup luksClose $crypt_label &&
+	Exit "Not able to cleanly close crypt" &&
+	return 40
 sync
 
 Echo "Ready for reboot!"
